import {
    LayoutDashboard, Users, Crosshair, Calendar,
    ScanLine, Wallet, Package, BarChart3, User, LogOut,
    Menu, X, ChevronDown, FileBarChart, Shield, CreditCard, Target,
    Building2, FolderOpen, Star, Shirt, ShoppingBag, ClipboardList, Timer, Eye,
    GraduationCap, CheckCircle, Bell, FileSearch, History, Truck,
    Trophy, TrendingUp, UserPlus, FileText, Award, Plus, ChevronLeft, ChevronRight, Home, Settings, MapPin, Store, HelpCircle
} from 'lucide-react';
import { ModuleName } from '../types/permissions';

export const NAV_ITEMS: { path: string; icon: any; label: string; module: ModuleName }[] = [
    { path: '/', icon: LayoutDashboard, label: 'Dashboard', module: 'dashboard' },
    { path: '/athletes', icon: Users, label: 'Athletes', module: 'athletes' },
    { path: '/schedules', icon: Calendar, label: 'Schedules', module: 'schedules' },
    { path: '/scoring', icon: Crosshair, label: 'Scoring', module: 'scoring' },
    { path: '/training/schedule', icon: Calendar, label: 'Training Schedule', module: 'athlete_training_schedule' },
    { path: '/archery-guidance', icon: Shield, label: 'Archery Guidance', module: 'athlete_archery_guidance' },
    { path: '/training/bleep-test', icon: Timer, label: 'Bleep Test', module: 'bleep_test' },
    { path: '/attendance', icon: ScanLine, label: 'Attendance', module: 'attendance' },
    { path: '/finance', icon: Wallet, label: 'Finance', module: 'finance' },
    { path: '/inventory', icon: Package, label: 'Inventory', module: 'inventory' },
    { path: '/analytics', icon: BarChart3, label: 'Analytics', module: 'analytics' },
    { path: '/reports', icon: FileBarChart, label: 'Reports', module: 'reports' },
    { path: '/digital-card', icon: CreditCard, label: 'Digital ID Card', module: 'digitalcard' },
    { path: '/settings/archer', icon: Target, label: 'Archer Config', module: 'archerconfig' },
    { path: '/club/structure', icon: Building2, label: 'Organization', module: 'organization' },
    { path: '/manpower', icon: Users, label: 'Manpower Management', module: 'manpower' },
    { path: '/files', icon: FolderOpen, label: 'File Manager', module: 'filemanager' },
    { path: '/admin/perpani', icon: Building2, label: 'Perpani Management', module: 'perpani_management' },
    { path: '/schools', icon: GraduationCap, label: 'Schools', module: 'schools' },

    { path: '/jersey/qc-station', icon: CheckCircle, label: 'QC Station', module: 'quality_control' },
    { path: '/notifications', icon: Bell, label: 'Notifications', module: 'notifications' },
    { path: '/audit-logs', icon: FileSearch, label: 'Audit Logs', module: 'audit_logs' },
    { path: '/history', icon: History, label: 'History', module: 'history' },
    { path: '/shipping', icon: Truck, label: 'Jersey Logistics', module: 'shipping' },
    { path: '/achievements', icon: Trophy, label: 'Achievements', module: 'achievements' },
    { path: '/analytics', icon: TrendingUp, label: 'Progress Charts', module: 'progress' },
    { path: '/coach/analytics', icon: BarChart3, label: 'Team Analytics', module: 'coach_analytics' },
    { path: '/finance/invoicing', icon: FileText, label: 'Invoicing', module: 'invoicing' },
    { path: '/payments', icon: CreditCard, label: 'Payments', module: 'payments' },
    { path: '/o2sn-registration', icon: Trophy, label: 'O2SN Registration', module: 'o2sn_registration' },
    { path: '/club/approvals', icon: Building2, label: 'Club Approval', module: 'club_approval' },
    { path: '/club/permissions', icon: Shield, label: 'Club Panel', module: 'club_permissions' },
    { path: '/licensing', icon: Award, label: 'Licensing', module: 'licensing' },
    { path: '/events/modular', icon: Plus, label: 'Create Event (Modular)', module: 'event_creation' },
    { path: '/reports/enhanced', icon: FileBarChart, label: 'Enhanced Reports', module: 'enhanced_reports' },
    { path: '/attendance-history', icon: Calendar, label: 'Attendance History', module: 'attendance_history' },
    { path: '/event-registration', icon: Users, label: 'Registrations', module: 'event_registration' },
    { path: '/event-results', icon: Trophy, label: 'Results', module: 'event_results' },
    { path: '/score-validation', icon: Target, label: 'Score Validation', module: 'score_validation' },
    { path: '/events', icon: Calendar, label: 'Event Management', module: 'events' },
    { path: '/admin', icon: Shield, label: 'Admin Panel', module: 'admin' },
    { path: '/marketplace', icon: Package, label: 'Csystem Market', module: 'catalog' },
    { path: '/order-history', icon: ShoppingBag, label: 'Order History', module: 'my_orders' },
    { path: '/jersey/admin', icon: LayoutDashboard, label: 'Jersey Dashboard', module: 'jersey_dashboard' },
    { path: '/jersey/admin/orders', icon: ClipboardList, label: 'Purchase Orders (PO)', module: 'jersey_orders' },
    { path: '/jersey/admin/orders', icon: Timer, label: 'Timeline Monitor', module: 'jersey_timeline' },
    { path: '/jersey/admin/products', icon: Shirt, label: 'Products', module: 'jersey_products' },

    { path: '/club/units', icon: MapPin, label: 'Units', module: 'units' },
];
