/**
 * Seed script to populate Troubleshoot entries from TROUBLESHOOTING.md
 * Run with: npx tsx scripts/seed-troubleshoot.ts
 */

import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const TROUBLESHOOT_ENTRIES = [
    {
        tsId: 'TS-001',
        title: 'Login 401 Unauthorized',
        category: 'Authentication',
        severity: 'High',
        effort: 'Quick',
        symptoms: 'User enters correct credentials but receives 401 Unauthorized.\nServer logs show POST /api/v1/auth/login requests reaching the server.\nMultiple login attempts all fail.',
        rootCause: 'Password hash mismatch in the database. The stored passwordHash does not match the password being entered.',
        debugSteps: '1. Check server logs for POST /api/v1/auth/login requests.\n2. Run scripts/check-admin.ts to verify user exists and is active.\n3. If user exists, the password hash is likely incorrect.',
        solution: 'Run the password reset script:\ncd server\nnpx tsx scripts/reset-admin-password.ts',
        prevention: 'Always use bcrypt.hash() when setting passwords programmatically.\nNever manually edit passwordHash in the database.',
        relatedFiles: 'server/src/controllers/auth.controller.ts, server/scripts/reset-admin-password.ts',
    },
    {
        tsId: 'TS-002',
        title: 'Prisma Client EPERM Error',
        category: 'Database',
        severity: 'Medium',
        effort: 'Medium',
        symptoms: 'EPERM: operation not permitted error when running npm run db:generate:local.\nPrisma Client files are locked.',
        rootCause: 'The server process (npx tsx watch) is holding a lock on Prisma Client files, preventing regeneration.',
        debugSteps: '1. Check for running server processes: netstat -ano | findstr :5000\n2. Identify the PID of the server process.',
        solution: '1. Stop all server processes (Ctrl+C in server terminal).\n2. Run npm run db:generate:local.\n3. Restart the server.',
        prevention: 'Always stop the server before regenerating Prisma Client.',
        relatedFiles: 'server/prisma/schema.dev.prisma, server/README_PRISMA.md',
    },
    {
        tsId: 'TS-003',
        title: 'EADDRINUSE Port 5000',
        category: 'Backend',
        severity: 'Medium',
        effort: 'Quick',
        symptoms: 'Server fails to start with EADDRINUSE: address already in use :::5000.',
        rootCause: 'Another process is already using port 5000 (often a zombie Node process or another server instance).',
        debugSteps: 'netstat -ano | findstr :5000\nIdentify the PID using port 5000.',
        solution: 'Kill the offending process:\ntaskkill /PID <PID> /F\nThen restart the server.',
        prevention: 'Use Ctrl+C to properly stop servers instead of closing terminals.',
        relatedFiles: 'server/src/index.ts',
    },
    {
        tsId: 'TS-004',
        title: 'Avatar Upload 500 Error',
        category: 'API',
        severity: 'High',
        effort: 'Quick',
        symptoms: 'Profile picture upload fails with a 500 Internal Server Error.\nConsole shows CORS or proxy errors.',
        rootCause: 'Vite proxy in client/vite.config.ts is pointing to the wrong backend port.',
        debugSteps: '1. Check client/vite.config.ts for proxy target.\n2. Verify backend is running on the expected port.\n3. Check server logs for the actual listening port.',
        solution: 'Ensure vite.config.ts proxy matches the server port.',
        prevention: 'Standardize backend port in .env and vite.config.ts.',
        relatedFiles: 'client/vite.config.ts, server/src/index.ts',
    },
    {
        tsId: 'TS-005',
        title: 'File Manager Blinking',
        category: 'UI',
        severity: 'Medium',
        effort: 'Medium',
        symptoms: 'File Manager modal appears briefly then disappears repeatedly.\nContent flickers when modal is open.',
        rootCause: 'Body scroll lock was not properly managed, causing re-renders and state conflicts.',
        debugSteps: 'Check useEffect hooks for side effects that might cause re-renders.',
        solution: 'Implement body scroll lock using useEffect with cleanup.',
        prevention: 'Always manage body scroll lock when rendering modals.\nUse React Portal for modal rendering.',
        relatedFiles: 'client/src/components/documents/FileManager.tsx',
    },
    {
        tsId: 'TS-006',
        title: 'Sidebar Module Not Appearing',
        category: 'UI',
        severity: 'Medium',
        effort: 'Quick',
        symptoms: 'New module added to permissions but does not appear in sidebar.',
        rootCause: 'Module was added to permissions.ts but not to NAV_ITEMS in DashboardLayout.tsx.',
        debugSteps: '1. Check client/src/types/permissions.ts for module definition.\n2. Check client/src/components/layout/DashboardLayout.tsx for NAV_ITEMS entry.\n3. Check if module has correct roles array.',
        solution: 'Add the module to both permissions.ts AND DashboardLayout.tsx.',
        prevention: 'Always update both permissions.ts AND DashboardLayout.tsx when adding modules.',
        relatedFiles: 'client/src/types/permissions.ts, client/src/components/layout/DashboardLayout.tsx',
    },
    {
        tsId: 'TS-007',
        title: 'Club Panel Access Denied',
        category: 'Authentication',
        severity: 'Medium',
        effort: 'Quick',
        symptoms: 'Super Admin cannot access /club/permissions route.\nRedirected to dashboard or shown access denied.',
        rootCause: 'ClubRoute wrapper in App.tsx did not include SUPER_ADMIN in allowed roles.',
        debugSteps: 'Check the ClubRoute component in App.tsx for role restrictions.',
        solution: 'Add SUPER_ADMIN to the role check in ClubRoute.',
        prevention: 'When creating role-restricted routes, always consider if Super Admin should have access.',
        relatedFiles: 'client/src/App.tsx',
    },
    {
        tsId: 'TS-008',
        title: 'CORS Blocked Origin in Production',
        category: 'Deployment',
        severity: 'High',
        effort: 'Quick',
        symptoms: 'API requests from app.corelink.id fail with CORS errors.\nBrowser console shows Access-Control-Allow-Origin errors.',
        rootCause: 'Production domain was not included in the CORS allowedOrigins array in server/src/index.ts.',
        debugSteps: 'Check server/src/index.ts for CORS configuration.',
        solution: 'Add the production domain to allowed origins array.',
        prevention: 'Always update CORS configuration when deploying to new domains.',
        relatedFiles: 'server/src/index.ts',
    },
    {
        tsId: 'TS-009',
        title: 'Vercel 404 on Refresh',
        category: 'Deployment',
        severity: 'High',
        effort: 'Quick',
        symptoms: 'SPA pages return 404 when refreshed or accessed directly.\nWorks on first load but fails on browser refresh.',
        rootCause: 'Vercel does not know to route all requests to index.html for client-side routing.',
        debugSteps: 'Check if vercel.json exists with proper rewrites.',
        solution: 'Create vercel.json with rewrites rule: { "source": "/(.*)", "destination": "/index.html" }',
        prevention: 'Always include vercel.json rewrites for SPAs deployed to Vercel.',
        relatedFiles: 'client/vercel.json',
    },
    {
        tsId: 'TS-010',
        title: 'TypeScript Config for Production Build',
        category: 'Build',
        severity: 'High',
        effort: 'Medium',
        symptoms: 'Build fails on Vercel/deployment with TypeScript errors.\nLocal build works but production build fails.',
        rootCause: 'Mismatched tsconfig.json settings between development and production. CommonJS vs ESM module resolution issues.',
        debugSteps: '1. Run npm run build locally to replicate.\n2. Check error messages for specific TS errors.',
        solution: 'Ensure consistent tsconfig.json settings with module: ESNext, moduleResolution: bundler, skipLibCheck: true.',
        prevention: 'Test production builds locally before deploying.',
        relatedFiles: 'client/tsconfig.json, server/tsconfig.json',
    },
    {
        tsId: 'TS-011',
        title: 'PWA Maskable Icon Issues',
        category: 'UI',
        severity: 'Low',
        effort: 'Quick',
        symptoms: 'PWA install shows cropped or misaligned app icon.\nIcon appears too large on home screen.',
        rootCause: 'Maskable icons require more padding (safe zone) than regular icons.',
        debugSteps: 'Test PWA icons with Chrome DevTools Application tab.',
        solution: 'Create maskable icon with 40% padding around the central logo.',
        prevention: 'Always test PWA icons with Chrome DevTools Application tab.',
        relatedFiles: 'client/public/manifest.json, client/public/icons/',
    },
    {
        tsId: 'TS-012',
        title: 'Onboarding Data Not Persisting',
        category: 'API',
        severity: 'High',
        effort: 'Medium',
        symptoms: 'WhatsApp number and Province/City entered during onboarding are not saved.\nData appears lost after registration.',
        rootCause: 'Frontend was not sending provinceId, cityId, whatsapp in registration request.\nBackend validation schema was not accepting these fields.',
        debugSteps: 'Check network tab for registration request payload.',
        solution: 'Update frontend registration call to include location fields.\nUpdate backend registerSchema to accept optional fields.',
        prevention: 'Verify all form fields are included in API request payload.',
        relatedFiles: 'client/src/pages/OnboardingPage.tsx, server/src/routes/auth.routes.ts',
    },
    {
        tsId: 'TS-013',
        title: 'View As Auto-Navigation Issue',
        category: 'UI',
        severity: 'Medium',
        effort: 'Medium',
        symptoms: 'Super Admin View As search field causes immediate navigation while typing.\nSystem resets to Super Admin profile before user finishes typing SIP ID.',
        rootCause: 'useEffect was triggering API calls on every character change instead of on user confirmation.',
        debugSteps: 'Check Header.tsx for useEffect dependencies triggering fetches.',
        solution: 'Implement debounced input with explicit confirmation.\nOnly trigger simulation on Enter key or dropdown selection.',
        prevention: 'Always debounce user input before triggering API calls.',
        relatedFiles: 'client/src/components/layout/Header.tsx, client/src/context/AuthContext.tsx',
    },
    {
        tsId: 'TS-014',
        title: 'Coach Score Submission Blocked',
        category: 'API',
        severity: 'High',
        effort: 'Quick',
        symptoms: 'Athletes cannot save their own scoring sessions.\nSubmit returns 403 Forbidden.',
        rootCause: 'Backend /scores/submit endpoint only allowed COACH role, not ATHLETE.',
        debugSteps: 'Check score.routes.ts for role restrictions.',
        solution: 'Make coachId optional in ScoringRecord model.\nUpdate route to allow ATHLETE role.',
        prevention: 'Consider self-service use cases when designing role-restricted endpoints.',
        relatedFiles: 'server/src/routes/score.routes.ts, server/prisma/schema.dev.prisma',
    },
    {
        tsId: 'TS-015',
        title: 'Multi-Role System Import Errors',
        category: 'Build',
        severity: 'Medium',
        effort: 'Quick',
        symptoms: 'AddRolePage.tsx and RoleRequestsAdminPage.tsx throw import errors.\nComponents reference non-existent exports.',
        rootCause: 'Circular dependencies or missing exports in shared type files after multi-role refactoring.',
        debugSteps: 'Run tsc --noEmit to see all import errors.',
        solution: 'Verify all imported types exist in source files.\nUse export type { X } for type-only exports.',
        prevention: 'Run tsc --noEmit before committing to catch import errors.',
        relatedFiles: 'client/src/pages/AddRolePage.tsx, client/src/pages/RoleRequestsAdminPage.tsx',
    },
    {
        tsId: 'TS-016',
        title: 'Profile Controller Duplicate Identifier',
        category: 'Backend',
        severity: 'High',
        effort: 'Quick',
        symptoms: 'Profile update endpoint fails with Duplicate identifier TypeScript error.\nLines 259-260 of profile.controller.ts show compilation errors.',
        rootCause: 'Variable name collision in the controller code - two variables with the same name in the same scope.',
        debugSteps: 'Check TypeScript compilation errors in profile.controller.ts.',
        solution: 'Rename one of the conflicting variables.',
        prevention: 'Use descriptive variable names that reflect their purpose.',
        relatedFiles: 'server/src/controllers/profile.controller.ts',
    },
    {
        tsId: 'TS-017',
        title: 'Prisma Upsert Missing Required Field',
        category: 'Database',
        severity: 'High',
        effort: 'Medium',
        symptoms: 'Athlete profile creation fails with Argument dateOfBirth is missing error.\nPrisma upsert operation throws validation error.',
        rootCause: 'When using Prisma upsert, the create payload must explicitly include all required fields.',
        debugSteps: 'Check Prisma error logs for missing field names.',
        solution: 'Explicitly construct the create payload for Prisma upsert with all required fields.',
        prevention: 'Always explicitly define create payloads for upsert operations.',
        relatedFiles: 'server/src/controllers/profile.controller.ts',
    },
    {
        tsId: 'TS-018',
        title: 'Shell Redirection File Corruption',
        category: 'Build',
        severity: 'Critical',
        effort: 'Long',
        symptoms: 'File grows to 100MB+ unexpectedly.\nVS Code/Cursor becomes unresponsive.\nFile deletion fails with file in use error.',
        rootCause: 'Using shell redirection commands like type file >> file causes infinite recursion.',
        debugSteps: '1. Check file size immediately if editor becomes sluggish.\n2. If file is massive, kill the editor process FIRST.',
        solution: '1. Kill VS Code/Cursor via Task Manager.\n2. Delete the corrupted file.\n3. Restore from git: git checkout -- filename.ts',
        prevention: 'NEVER use >> redirection to append a file to itself.',
        relatedFiles: 'Any file that was target of redirection',
    },
    {
        tsId: 'TS-019',
        title: 'Agent Password Reset Deviation',
        category: 'Authentication',
        severity: 'Medium',
        effort: 'Quick',
        symptoms: 'Standard credentials in README.md don\'t work.\nLogin fails despite using documented password.',
        rootCause: 'Agent or developer reset password to temporary value (admin123) and didn\'t update README.',
        debugSteps: 'Check server/scripts for custom reset scripts.',
        solution: '1. Try common passwords: admin123, 123456.\n2. Reset using reset-admin-password.ts.',
        prevention: 'Always use README credentials first.\nUpdate README if password changes.',
        relatedFiles: 'README.md, server/scripts/reset-admin-password.ts',
    },
];

async function main() {
    console.log('🔧 Seeding Troubleshoot entries...\n');

    for (const entry of TROUBLESHOOT_ENTRIES) {
        try {
            await (prisma as any).troubleshoot.upsert({
                where: { tsId: entry.tsId },
                create: {
                    ...entry,
                    createdBy: 'system-seed',
                },
                update: entry,
            });
            console.log(`✅ ${entry.tsId}: ${entry.title}`);
        } catch (error) {
            console.error(`❌ ${entry.tsId}: Failed -`, error);
        }
    }

    console.log(`\n🎉 Done! Seeded ${TROUBLESHOOT_ENTRIES.length} entries.`);
}

main()
    .catch(console.error)
    .finally(() => prisma.$disconnect());
